### ISSUE TITLE
Using this program cannot be detected

### ISSUE THREAD

**Issue by q1085909155** [sapphonie/StAC-tf2#130]
My players tell me and my observations that illegal players using Lmaobox programs go undetected. It's not even logged.
![DFD164ADAEFF5B0254F5C1EFD56CEBA4](https://user-images.githubusercontent.com/69096633/188261345-93360fca-dcf9-4a5c-bbef-ce78bc68bdec.png)

**Comment by q1085909155** [comment]
It has been tested many times. Even the use of violence will not be detected by STAC

**Comment by sapphonie** [comment]
Ok, this isn't really a bug report. StAC can't possibly catch everything, though you're probably expecting it to catch people instantly, which it won't, since it needs to accumulate detections. Unless you can demonstrate that StAC is being *bypassed* or that there's an actual bug, I'm gonna close this
