### ISSUE TITLE
[SUGGESTION] Auto record capabilites?

### ISSUE THREAD

**Issue by ratawar** [sapphonie/StAC-tf2#2]
I was wondering if there was a chance to implement an auto-record feature like [Little AC](https://forums.alliedmods.net/showthread.php?t=325115) or [SMAC](https://forums.alliedmods.net/showthread.php?p=1861742) have, it'd be awesome and really useful.

**Comment by sapphonie** [comment]
I've gotten this request and others like "log detections to a file instead of just STV & admin chat" from comp leagues as well. On the servers I run and manage, I always have STV recording *anyway* with https://forums.alliedmods.net/showthread.php?p=824438 OR they're comp servers which auto record stv on their own as well. I can definitely look into it.

**Comment by ratawar** [comment]
Sounds fair enough, I'll look into Autorecorder, thanks a lot!
