### ISSUE TITLE
32-bit versions of TF2 get falsely detected due to windows_speaker_config

### ISSUE THREAD

**Issue by Reycko** [sapphonie/StAC-tf2#206]
`windows_speaker_config` was removed in 64bit but remains on 32bit so if anyone with a 32-bit PC plays on a server with StAC they will get banned for cheating

**Comment by sapphonie** [comment]
x86 players can not connect to up to date tf2 servers (regardless of if the servers themselves are x86 or x64)

**Comment by sapphonie** [comment]
Wrong!

**Comment by sapphonie** [comment]
https://github.com/ValveSoftware/Source-1-Games/issues/5777

**Comment by sapphonie** [comment]
I genuinely don't have an answer for what should be done about this. Valve continues to be completely clueless anticheat wise, they've stated this is intentional. I don't think there's any legitimate reason why 32 bit clients should be able to connect to up to date servers after the 64 bit update. I genuinely can not think of one that isn't either malicious or something that just should not  be catered to. I'm leaving this ban in StAC as it is, but if there's enough outcry I may toss it. Opinions / comments welcome.

**Comment by slender100** [comment]
> I genuinely don't have an answer for what should be done about this. Valve continues to be completely clueless anticheat wise, they've stated this is intentional. I don't think there's any legitimate reason why 32 bit clients should be able to connect to up to date servers after the 64 bit update. I genuinely can not think of one that isn't either malicious or something that just should not be catered to. I'm leaving this ban in StAC as it is, but if there's enough outcry I may toss it. Opinions / comments welcome.

Multi-billion dollar company btw.

**Comment by AzureWoof** [comment]
Thank you for acknowledging the stupidity of this. The response I got from my post genuinely irritated me to no end for months. It isn't "impossible" to stop people from connecting to official servers on the 32 bit client because "they can just bytepatch it lol". This is a multi-billion dollar company that for some reason willingly chooses to understaff itself despite the constant need for basic maintenance in their games that they _**do not**_ provide. They could easily stop people from doing this if they applied literally any level of resources towards TF2. It's unacceptable and I shouldn't feel like an idiot for stating the obvious.

**Comment by sapphonie** [comment]
Per internal conversation with a Valve contractor, this decision was made due to the sheer amount of players on 32 bit versions of Windows, which I, again, do not believe should be catered to. That being said, I'm likely going to have to change this ban to a kick because there's legitimately no way to determine if these players are actually using cathook (which was why the cvar was added to StACs cvar detection matrix in the first place, as cathook would create this cvar to spoof Windows detection plugins), and I don't want to ban players for not cheating.

**Comment by sapphonie** [comment]
Double wrong. Verified that this cvar doesn't exist on latest x86

![image](https://github.com/user-attachments/assets/30b26242-b5a9-4c63-9216-77e9681f869d)

**Comment by sapphonie** [comment]
If the cvar doesn't exist on latest x86 than this issue is moot (for StAC) and StAC will continue to ban for this cvar because it's indicative of outdated clients (which shouldn't be able to connect to new servers without memory modification) or cheating clients (duh)

**Comment by Reycko** [comment]
> Per internal conversation with a Valve contractor, this decision was made due to the sheer amount of players on 32 bit versions of Windows, which I, again, do not believe should be catered to. That being said, I'm likely going to have to change this ban to a kick because there's legitimately no way to determine if these players are actually using cathook (which was why the cvar was added to StACs cvar detection matrix in the first place, as cathook would create this cvar to spoof Windows detection plugins), and I don't want to ban players for not cheating.

I find this really stupid. Even Microsoft stopped making 32-bit builds since the first release Windows 11 (oct 2021).
